version: "3.8"

services:
  backend:
    build: ./backend
    container_name: bowling_backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY} # Ensure .env file exists with this key
    volumes:
      - backend-data:/app
    depends_on:
      - frontend
    networks:
      - bowling-net

  frontend:
    build: ./frontend
    container_name: bowling_frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend-data:/app
    networks:
      - bowling-net

volumes:
  backend-data:
  frontend-data:

networks:
  bowling-net:
    driver: bridge
