name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Backend Pylint Tests
  backend_linting:
    name: Backend Pylint Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pylint  # Install pylint

      - name: Run Pylint
        run: |
          echo "Running Pylint on all backend files..."
          pylint backend/app backend/tests

  # Backend Unit Tests
  backend_unit_tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Unit Tests
        run: |
          echo "Running Backend Unit Tests..."
          pytest backend/tests/unit/test_game_logic.py

  # Backend Integration Tests
  backend_integration_tests:
    name: Backend Integration Tests
    runs-on: ubuntu-latest
    needs: backend_unit_tests # Run only if unit tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Integration Tests
        run: |
          echo "Running Backend Integration Tests..."
          pytest backend/tests/integration/test_endpoints.py

  # Placeholder for future frontend tests
  frontend_tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: backend_integration_tests # Run after backend tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Tests
        run: |
          echo "Running Frontend Tests..."
          npm test
